### PR TITLE
Mention the tmpfs in container problem in README

### PR DESCRIPTION
**Pull request by jpic**

### CODE REVIEW

**Comment by Mic92** [comment]
Never thought about that, but this really affects every filesystem mounted to /tmp and or /, which is not directly accessible to the hosts mount namespace. A possible solution could be to invoke a shell inside the container and pipe into this process to create the file, which I wanted to avoid, because it would further slow down ansible. I keep this open as a bug.

**Comment by jpic** [comment]
> A possible solution could be to invoke a shell inside the container and pipe into this process to create the file, which I wanted to avoid, because it would further slow down ansible.

Maybe it could be an option ?

**Comment by Mic92** [comment]
fixed in a6231fbc388a6d81f5333764ba13e6b47687827d

**Comment by Mic92** [comment]
The overhead isn't actually that bad, because the plugin just forks the python process to enter the namespace now.

**Pull request closed without merging**
